### ISSUE TITLE
Sisu "strict" behaviour but locally

### ISSUE THREAD

**Issue by cstamas** [eclipse-sisu/sisu-project#178]
Right now we can make Sisu "strict" (is strict in Maven 4) but in Maven 3 it is "not strict". This makes impossible following use case: assume a Maven extension that should work in both, Maven 3 and Maven 4.

Assume it has two components, one implementing Maven 3 API iface and one implementing Maven 4 API iface.

Use in Maven 3 is "ok", as it is not "strict", and due absence of Maven 4 API in Maven 3, loading of component would fail, and due non-strictness, it would be silently skipped as well. Good.

But in Maven 4, due strictness, ASSUMING Maven 3 iface is gone, it would explode.

Using words like "locally" (as opposed to "globally" that current implementation is), as we may want to make it strict for Maven core, but (we reuse same container) lax the container when we look for extension components?

**Comment by kwin** [comment]
This has been caused by #97.

**Comment by kwin** [comment]
The question is whether we would need the possibility to make a component both lenient on a consumer as well as on the provider side or only on provider side (like for this use case).

**Comment by cstamas** [comment]
Just some ideas: this local info (for strictness) may come from index maybe? Examples:
```
org.apache.maven.lifecycle.MyParticipant;ignoreIfFail=true
org.apache.maven.lifecycle.MyOtherParticipant;condition=mycondition
```

But some sort of programmatic API would be good as well, as I said, we may want Maven to "boot" in strict mode (ensure all is set as expected), but while discovering components of later loaded extension/plugin we may want to "lax" it?

**Comment by kwin** [comment]
IMHO strict should just be effective for class parsing exceptions. A simple CNFE/NoClassDefFoundError should not lead to an exception. @cstamas Can you share a stacktrace of a false strictness?

**Comment by kwin** [comment]
Relates to https://issues.apache.org/jira/browse/MNG-8614. My proposal is that every `LinkageError` (https://docs.oracle.com/javase/8/docs/api/java/lang/LinkageError.html) except for `NoClassDefFoundError` should lead to an exception. That way obvious issues are very visible, but not finding a class in the classpath at run time is still silently ignored!
